apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tms-varsel-test"
  namespace: "min-side"
  labels:
    "team": "min-side"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/tms-varsel-test/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/tms-varsel-test/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
  ingresses:
    - "https://www.dev.nav.no/tms-varsel-test"
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tms-event-test-producer
